import { CourseList } from "@/types/blog";

const CertificationData: CourseList[] = [
  {
    _id: 1,
    mainImage: "/images/cert/cert1.png",
    title: "ISO 9001:2015 – Quality Management Systems",
    metadata: "QMS",
    category: "Quality, Health & Environment Mgt",
    slug: "iso-9001-qms",
    status: 'paid',
    price: "250000"
  },
  {
    _id: 2,
    mainImage: "/images/cert/cert2.png",
    title: "ISO/IEC 27001:2022 – Information Security Management Systems",
    metadata: "ISMS",
    category: "Cyber & Privacy",
    slug: "iso-27001-isms",
    status: 'not-paid',
    price: "150000"
  },
  {
    _id: 3,
    mainImage: "/images/cert/cert3.png",
    title: "ISO 22301:2019 – Business Continuity Management Systems",
    metadata: "BCMS",
    category: "Business Management",
    slug: "iso-22301-bcms",
    status: 'not-paid',
    price: "120000"
  },
  {
    _id: 4,
    mainImage: "/images/cert/cert4.png",
    title: "ISO/IEC 20000:2018 – IT Service Management Systems",
    metadata: "ITSMS",
    category: "Info. Tech Mgt",
    slug: "iso-20000-itsms",
    status: 'not-paid',
    price: "150000"
  },
  {
    _id: 5,
    mainImage: "/images/cert/cert5.png",
    title: "ISO/IEC 27701:2019 – Privacy Information Management Systems",
    metadata: "PIMS",
    category: "Cyber & Privacy",
    slug: "iso-27701-pims",
    status: 'not-paid',
    price: "150000"
  },
  {
    _id: 6,
    mainImage: "/images/cert/cert6.png",
    title: "ISO/IEC 27017:2015 – Cloud Security",
    metadata: "CLOUD SECURITY",
    category: "Cyber & Privacy",
    slug: "iso-27017-cloud-security",
    status: 'not-paid',
    price: "150000"
  },
  {
    _id: 7,
    mainImage: "/images/cert/cert7.png",
    title: "ISO 26000:2010 – Social Responsibility",
    metadata: "CSR",
    category: "Business Management",
    slug: "iso-26000-csr",
    status: 'not-paid',
    price: "250000"
  },
  {
    _id: 8,
    mainImage: "/images/cert/cert8.png",
    title: "ISO/IEC 20022:2013 – Financial Messaging",
    metadata: "UFIMS",
    category: "Info. Tech Mgt",
    slug: "iso-20022-ufims",
    status: 'not-paid',
    price: "450000"
  },
  {
    _id: 9,
    mainImage: "/images/cert/cert9.png",
    title: "ISO 55001:2014 – Assets Management Systems",
    metadata: "AMS",
    category: "Business Management",
    slug: "iso-55001-ams",
  },
  {
    _id: 10,
    mainImage: "/images/cert/cert10.png",
    title: "ISO 31000:2018 – Risk Management",
    metadata: "RISK MANAGEMENT",
    category: "Business Management",
    slug: "iso-31000-risk-management",
  },
  {
    _id: 11,
    mainImage: "/images/cert/cert11.png",
    title: "ISO/IEC 29100:2024 – Privacy Framework",
    metadata: "PRIVACY FRAMEWORK",
    category: "Cyber & Privacy",
    slug: "iso-29100-privacy-framework",
  },
  {
    _id: 12,
    mainImage: "/images/cert/cert12.png",
    title: "ISO 41001:2018 – Facility Management Systems",
    metadata: "FMS",
    category: "Business Management",
    slug: "iso-41001-fms",
  },
  {
    _id: 13,
    mainImage: "/images/cert/cert13.png",
    title: "ISO/IEC 27005:2022 – Information Security Risk Management",
    metadata: "ISRM",
    category: "Cyber & Privacy",
    slug: "iso-27005-isrm",
  },
  {
    _id: 14,
    mainImage: "/images/cert/cert14.png",
    title: "ISO 22000:2018 – Food Safety Management Systems",
    metadata: "FSMS",
    category: "Quality, Health & Environment Mgt",
    slug: "iso-22000-fsms",
  },
  {
    _id: 15,
    mainImage: "/images/cert/cert15.png",
    title: "ISO 37500:2014 – Outsourcing",
    metadata: "OUTSOURCING",
    category: "Business Management",
    slug: "iso-37500-outsourcing",
  },
  {
    _id: 16,
    mainImage: "/images/cert/cert16.png",
    title: "ISO 37301:2021 – Compliance Management Systems",
    metadata: "CMS",
    category: "Business Management",
    slug: "iso-37301-cms",
  },
  {
    _id: 17,
    mainImage: "/images/cert/cert17.png",
    title: "SandBP Certified Data Protection Officer",
    metadata: "SCDPO",
    category: "Cyber & Privacy",
    slug: "sandbp-data-protection-officer",
  },
  {
    _id: 18,
    mainImage: "/images/cert/cert18.png",
    title: "SandBP System And Software Quality Guidelines",
    metadata: "SSQM",
    category: "Info. Tech Mgt",
    slug: "sandbp-ssqm",
  },
  {
    _id: 19,
    mainImage: "/images/cert/cert19.png",
    title: "ISO 14090:2019 – Climate Change",
    metadata: "CLIMATE CHANGE",
    category: "Quality, Health & Environment Mgt",
    slug: "iso-14090-climate-change",
  },
  {
    _id: 20,
    mainImage: "/images/cert/cert20.png",
    title: "ISO 19011:2018 – Internal Auditor",
    metadata: "INTERNAL AUDITOR",
    category: "MS Audit",
    slug: "iso-19011-internal-auditor",
  },
  {
    _id: 21,
    mainImage: "/images/cert/cert21.png",
    title: "SandBP Certified Cybersecurity Professional",
    metadata: "Cybersecurity",
    category: "Cyber & Privacy",
    slug: "sandbp-cybersecurity-professional",
  },
  {
    _id: 22,
    mainImage: "/images/cert/cert22.png",
    title: "ISO 10002:2018 – Customer Satisfaction Management",
    metadata: "CSM",
    category: "Business Management",
    slug: "iso-10002-csm",
  },
  {
    _id: 23,
    mainImage: "/images/cert/cert23.png",
    title: "ISO 45001:2018 – Occupational Health & Safety Management Systems",
    metadata: "OHSMS",
    category: "Quality, Health & Environment Mgt",
    slug: "iso-45001-ohsms",
  },
  {
    _id: 24,
    mainImage: "/images/cert/cert24.png",
    title: "ISO 14001:2015 – Environmental Management Systems",
    metadata: "EMS",
    category: "Quality, Health & Environment Mgt",
    slug: "iso-14001-ems",
  },
  {
    _id: 25,
    mainImage: "/images/cert/cert25.png",
    title: "ISO/IEC 27035:2023 – Information Security Incident Management",
    metadata: "ISIM",
    category: "Cyber & Privacy",
    slug: "iso-27035-isim",
  },
  {
    _id: 26,
    mainImage: "/images/cert/cert26.png",
    title: "ISO 8583 – Payment Transaction Processing Fundamentals",
    metadata: "PTP",
    category: "Info. Tech Mgt",
    slug: "iso-8583-ptp",
  },
  {
    _id: 27,
    mainImage: "/images/cert/cert27.png",
    title: "ISO 30301:2019 – Management Systems for Records",
    metadata: "MSR",
    category: "Business Management",
    slug: "iso-30301-msr",
  },
];

export default CertificationData;
